export default {
    ADD_TABLE: 'ADD_TABLE',
    SHOW_TABLE: 'SHOW_TABLE',
    ORDER_FOOD: 'ORDER_FOOD',
    UPDATE_TABLE: 'UPDATE_TABLE',
    ADD_RECORD: 'ADD_RECORD',
    TABLE_LOADING: 'TABLE_LOADING'
}