export default {
    USER_REGISTERED: 'USER_REGISTERED',
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    ADD_TABLE: 'ADD_TABLE',
    SHOW_TABLE: 'SHOW_TABLE',
    ORDER_FOOD: 'ORDER_FOOD',
    REMOVE_FOOD: 'REMOVE_FOOD',
    UPDATE_TABLE: 'UPDATE_TABLE',
    RESET_TABLE: 'RESET_TABLE',
    ADD_RECORD: 'ADD_RECORD',
    TABLE_LOADING: 'TABLE_LOADING'
}